name: Update README with Commit Proportions
description: 'Update the readme with a pie chart at the end, showing the proportion of commits by each author of the repository.'
inputs:
  readme:
    description: 'Path to the README file'
    required: true
    default: 'README.md'
  token:
    description: 'GitHub token'
    required: true
branding:
  icon: 'pie-chart'
  color: 'green'

permissions:
  contents: write

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        path: repo

    - name: Checkout action code
      uses: actions/checkout@v4
      with:
        repository: HaGeza/GHCPR
        path: action_repo

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Fetch commit authors
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        REPO: ${{ github.repository }}
      run: |
        gh api -H "Accept: application/vnd.github+json" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               /repos/$REPO/commits > action_repo/commit_authors.json
              
        
    - name: Update README with custom script
      shell: bash
      run: |
        cd action_repo
        python generate_chart.py commit_authors.json ../repo/${{ inputs.readme }}
        cd ..

    - name: Commit and push changes
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        AUTHOR_NAME: GHCPR_BOT
        AUTHOR_EMAIL: ghcprbot@users.noreply.github.com
        REPO: ${{ github.repository }}
      run: |
        cd repo
        git config user.name "${{ env.AUTHOR_NAME }}"
        git config user.email "${{ env.AUTHOR_EMAIL }}"
        git add ${{ inputs.readme }}
        git commit --allow-empty --author="${{ env.AUTHOR_NAME }} <${{ env.AUTHOR_EMAIL }}>" -m "GHCPR: Update README with commit proportions"
        git push
        cd ..
    